apiVersion: v1
kind: Service
metadata:
  name: react-svc-lb
  labels:
    app: msa
    tier: frontend
spec:
  selector:
    app: msa
    tier: frontend
  ports:
    - port: 3000
      # name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa
      tier: frontend
  template:
    metadata:
      labels:
        app: msa
        tier: frontend
    spec:
      containers:
        - name: react
          image: ddung1203/react-crud:35
          ports:
          - containerPort: 3000